<?php

namespace Database\Seeders;

use App\Models\SkillsSet;
use Illuminate\Database\Seeder;

class SkillsSetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $skillssets = [
            ['skill_category_id' => 12, 'skill_name' => '2D and 3D Animation'],
            ['skill_category_id' => 12, 'skill_name' => 'Accounting'],
            ['skill_category_id' => 1, 'skill_name' => 'Acting'],
            ['skill_category_id' => 3, 'skill_name' => 'Active Listening'],
            ['skill_category_id' => 10, 'skill_name' => 'Adapting'],
            ['skill_category_id' => 12, 'skill_name' => 'Agile Methodologies'],
            ['skill_category_id' => 5, 'skill_name' => 'Assessing'],
            ['skill_category_id' => 12, 'skill_name' => 'Blueprint Drafting'],
            ['skill_category_id' => 3, 'skill_name' => 'Body Language'],
            ['skill_category_id' => 5, 'skill_name' => 'Brainstorming'],
            ['skill_category_id' => 12, 'skill_name' => 'Budgeting'],
            ['skill_category_id' => 2, 'skill_name' => 'Calculating'],
            ['skill_category_id' => 8, 'skill_name' => 'Caring'],
            ['skill_category_id' => 12, 'skill_name' => 'Cinematography'],
            ['skill_category_id' => 12, 'skill_name' => 'Civil Engineering'],
            ['skill_category_id' => 12, 'skill_name' => 'Cloud Security'],
            ['skill_category_id' => 8, 'skill_name' => 'Coaching'],
            ['skill_category_id' => 9, 'skill_name' => 'Code-switching'],
            ['skill_category_id' => 12, 'skill_name' => 'Coding'],
            ['skill_category_id' => 8, 'skill_name' => 'Collaboration'],
            ['skill_category_id' => 12, 'skill_name' => 'Color Correction'],
            ['skill_category_id' => 8, 'skill_name' => 'Compassion'],
            ['skill_category_id' => 2, 'skill_name' => 'Computing'],
            ['skill_category_id' => 5, 'skill_name' => 'Conceptual Thinking'],
            ['skill_category_id' => 8, 'skill_name' => 'Conflict Management'],
            ['skill_category_id' => 12, 'skill_name' => 'Constructing'],
            ['skill_category_id' => 4, 'skill_name' => 'Content Management'],
            ['skill_category_id' => 4, 'skill_name' => 'Content Strategy'],
            ['skill_category_id' => 4, 'skill_name' => 'Content Writing'],
            ['skill_category_id' => 9, 'skill_name' => 'Conversing'],
            ['skill_category_id' => 5, 'skill_name' => 'Cost-benefit Analyzing'],
            ['skill_category_id' => 5, 'skill_name' => 'Creative Thinking'],
            ['skill_category_id' => 11, 'skill_name' => 'Crisis Management'],
            ['skill_category_id' => 3, 'skill_name' => 'Customer Service'],
            ['skill_category_id' => 12, 'skill_name' => 'Data Analysis'],
            ['skill_category_id' => 12, 'skill_name' => 'Data Entry'],
            ['skill_category_id' => 6, 'skill_name' => 'Data Visualization'],
            ['skill_category_id' => 5, 'skill_name' => 'Deductive Reasoning'],
            ['skill_category_id' => 10, 'skill_name' => 'Delegating'],
            ['skill_category_id' => 7, 'skill_name' => 'Digital Asset Management'],
            ['skill_category_id' => 10, 'skill_name' => 'Directing'],
            ['skill_category_id' => 3, 'skill_name' => 'Documenting'],
            ['skill_category_id' => 3, 'skill_name' => 'Editing'],
            ['skill_category_id' => 12, 'skill_name' => 'Editing Software'],
            ['skill_category_id' => 12, 'skill_name' => 'Editorial Images'],
            ['skill_category_id' => 8, 'skill_name' => 'Empathy'],
            ['skill_category_id' => 10, 'skill_name' => 'Employee Development'],
            ['skill_category_id' => 12, 'skill_name' => 'Encryption'],
            ['skill_category_id' => 12, 'skill_name' => 'Engineering'],
            ['skill_category_id' => 10, 'skill_name' => 'Envisioning'],
            ['skill_category_id' => 5, 'skill_name' => 'Evaluating'],
            ['skill_category_id' => 5, 'skill_name' => 'Evidence Collecting'],
            ['skill_category_id' => 12, 'skill_name' => 'Experimenting'],
            ['skill_category_id' => 9, 'skill_name' => 'Explaining'],
            ['skill_category_id' => 7, 'skill_name' => 'Financial Modeling'],
            ['skill_category_id' => 8, 'skill_name' => 'Flexibility'],
            ['skill_category_id' => 9, 'skill_name' => 'Following Etiquette'],
            ['skill_category_id' => 2, 'skill_name' => 'Forecasting'],
            ['skill_category_id' => 10, 'skill_name' => 'Goal-setting'],
            ['skill_category_id' => 11, 'skill_name' => 'Grammar'],
            ['skill_category_id' => 6, 'skill_name' => 'Graphic Design'],
            ['skill_category_id' => 2, 'skill_name' => 'Graphing'],
            ['skill_category_id' => 7, 'skill_name' => 'Health Care Administration'],
            ['skill_category_id' => 7, 'skill_name' => 'Home Inspection'],
            ['skill_category_id' => 5, 'skill_name' => 'Inductive reasoning'],
            ['skill_category_id' => 5, 'skill_name' => 'Inferring'],
            ['skill_category_id' => 10, 'skill_name' => 'Influencing'],
            ['skill_category_id' => 2, 'skill_name' => 'Information Processing'],
            ['skill_category_id' => 3, 'skill_name' => 'Inquiring'],
            ['skill_category_id' => 8, 'skill_name' => 'Inspiring'],
            ['skill_category_id' => 6, 'skill_name' => 'Interior Design'],
            ['skill_category_id' => 9, 'skill_name' => 'Interpreting'],
            ['skill_category_id' => 11, 'skill_name' => 'Interviewing'],
            ['skill_category_id' => 9, 'skill_name' => 'Introducing'],
            ['skill_category_id' => 12, 'skill_name' => 'Intrusion Detection Software'],
            ['skill_category_id' => 2, 'skill_name' => 'Investigating'],
            ['skill_category_id' => 11, 'skill_name' => 'Keyword Research'],
            ['skill_category_id' => 6, 'skill_name' => 'Layout Development'],
            ['skill_category_id' => 12, 'skill_name' => 'Machine Learning'],
            ['skill_category_id' => 10, 'skill_name' => 'Managing'],
            ['skill_category_id' => 8, 'skill_name' => 'Mediating'],
            ['skill_category_id' => 10, 'skill_name' => 'Mentoring'],
            ['skill_category_id' => 2, 'skill_name' => 'Modeling'],
            ['skill_category_id' => 8, 'skill_name' => 'Motivating'],
            ['skill_category_id' => 3, 'skill_name' => 'Negotiating'],
            ['skill_category_id' => 12, 'skill_name' => 'Network Administration'],
            ['skill_category_id' => 8, 'skill_name' => 'Networking'],
            ['skill_category_id' => 7, 'skill_name' => 'Nursing'],
            ['skill_category_id' => 5, 'skill_name' => 'Observing'],
            ['skill_category_id' => 3, 'skill_name' => 'Open-mindedness'],
            ['skill_category_id' => 12, 'skill_name' => 'Operating Equipment'],
            ['skill_category_id' => 12, 'skill_name' => 'Operating Systems'],
            ['skill_category_id' => 2, 'skill_name' => 'Organizing'],
            ['skill_category_id' => 8, 'skill_name' => 'Patience'],
            ['skill_category_id' => 10, 'skill_name' => 'Performance Reviewing'],
            ['skill_category_id' => 11, 'skill_name' => 'Performance Tracking'],
            ['skill_category_id' => 6, 'skill_name' => 'Photo and Video Editing'],
            ['skill_category_id' => 6, 'skill_name' => 'Photo Composition'],
            ['skill_category_id' => 6, 'skill_name' => 'Photo Retouching'],
            ['skill_category_id' => 12, 'skill_name' => 'Photography'],
            ['skill_category_id' => 10, 'skill_name' => 'Planning'],
            ['skill_category_id' => 7, 'skill_name' => 'Plumbing'],
            ['skill_category_id' => 8, 'skill_name' => 'Positivity'],
            ['skill_category_id' => 2, 'skill_name' => 'Predicting'],
            ['skill_category_id' => 3, 'skill_name' => 'Presenting'],
            ['skill_category_id' => 7, 'skill_name' => 'Print Layout'],
            ['skill_category_id' => 5, 'skill_name' => 'Problem-solving'],
            ['skill_category_id' => 12, 'skill_name' => 'Processing'],
            ['skill_category_id' => 12, 'skill_name' => 'Product Developing'],
            ['skill_category_id' => 12, 'skill_name' => 'Programming'],
            ['skill_category_id' => 9, 'skill_name' => 'Proofreading'],
            ['skill_category_id' => 9, 'skill_name' => 'Public Speaking'],
            ['skill_category_id' => 12, 'skill_name' => 'Quality Controlling'],
            ['skill_category_id' => 9, 'skill_name' => 'Reinterpreting'],
            ['skill_category_id' => 8, 'skill_name' => 'Reliability'],
            ['skill_category_id' => 12, 'skill_name' => 'Repairing'],
            ['skill_category_id' => 9, 'skill_name' => 'Rephrasing'],
            ['skill_category_id' => 3, 'skill_name' => 'Reporting'],
            ['skill_category_id' => 9, 'skill_name' => 'Representing'],
            ['skill_category_id' => 2, 'skill_name' => 'Research'],
            ['skill_category_id' => 12, 'skill_name' => 'Restoring'],
            ['skill_category_id' => 2, 'skill_name' => 'Risk Analysis'],
            ['skill_category_id' => 11, 'skill_name' => 'Scheduling'],
            ['skill_category_id' => 11, 'skill_name' => 'Search Engine Marketing'],
            ['skill_category_id' => 12, 'skill_name' => 'SEO Tools'],
            ['skill_category_id' => 9, 'skill_name' => 'Signaling'],
            ['skill_category_id' => 5, 'skill_name' => 'Simplifying'],
            ['skill_category_id' => 7, 'skill_name' => 'Social Media'],
            ['skill_category_id' => 12, 'skill_name' => 'Sound Effects'],
            ['skill_category_id' => 8, 'skill_name' => 'Sourcing Feedback'],
            ['skill_category_id' => 9, 'skill_name' => 'Speaking'],
            ['skill_category_id' => 12, 'skill_name' => 'Spreadsheet Building'],
            ['skill_category_id' => 2, 'skill_name' => 'Statistical Analysis'],
            ['skill_category_id' => 3, 'skill_name' => 'Storytelling'],
            ['skill_category_id' => 3, 'skill_name' => 'Storytelling'],
            ['skill_category_id' => 5, 'skill_name' => 'Streamlining'],
            ['skill_category_id' => 3, 'skill_name' => 'Streamlining'],
            ['skill_category_id' => 3, 'skill_name' => 'Streamlining'],
            ['skill_category_id' => 10, 'skill_name' => 'Supervising'],
            ['skill_category_id' => 2, 'skill_name' => 'Surveying'],
            ['skill_category_id' => 3, 'skill_name' => 'Teaching'],
            ['skill_category_id' => 12, 'skill_name' => 'Testing'],
            ['skill_category_id' => 7, 'skill_name' => 'Trade and Exchange Rates'],
            ['skill_category_id' => 10, 'skill_name' => 'Training'],
            ['skill_category_id' => 9, 'skill_name' => 'Translating'],
            ['skill_category_id' => 5, 'skill_name' => 'Troubleshooting'],
            ['skill_category_id' => 6, 'skill_name' => 'Typography'],
            ['skill_category_id' => 12, 'skill_name' => 'User Experience (UX) Design'],
            ['skill_category_id' => 6, 'skill_name' => 'User Experience Development'],
            ['skill_category_id' => 7, 'skill_name' => 'Video Post-production'],
            ['skill_category_id' => 6, 'skill_name' => 'Web Design'],
            ['skill_category_id' => 6, 'skill_name' => 'Wireframing'],
            ['skill_category_id' => 12, 'skill_name' => 'Word Processing'],
            ['skill_category_id' => 9, 'skill_name' => 'Writing'],
        ];

        foreach ($skillssets as $skillsset) {
            SkillsSet::firstOrCreate([
                'skill_category_id' => $skillsset['skill_category_id'],
                'skill_name' => $skillsset['skill_name']
            ]);
        }
    }
}
